### PR TITLE
Update for Obsidian 1.0

### LINKED ISSUE #20: [Bug] The pane does not refresh
Using the last (0.5.0) version, the tag navigator pane does not refresh when I interact with it. Only my first action (for instance, enabling the display of a certain tag category) is followed by a plugin refresh, but then on, any other action is not correctly rendered and I have to close and re-open the Tag pane for my actions being visible (plugin refreshed).

I’m using the 1.0.3 version of Obsidian, and below is the is the list of my activated plugins :
- Citations
- BRAT
- Pandoc
- Status bar pomodoro timer
- Text snippets
- Update time on edit
- Tag wrangler
- Frontmatter tag suggest

I tried to install the plugin with BRAT : same result. I also tried to disable all the plugins but the tag navigator and BRAT : same result.
Thanks for your work !

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Thanks for the awesome extension! I'll preface this change by saying _I have no idea what I'm doing_. I rarely write JS or do any kind of frontend work. The changes here are a best-effort attempt at getting this plugin working again with Obsidian 1.0.

I've updated the dependencies, fixed #20, and made a change to allow multiple independent views to be open simultaneously. I also picked up an accidental vscode auto-format along the way. I'm happy to split these changes into separate PRs if you'd prefer.

Thanks again :v:

---

Closes https://github.com/alexobenauer/obsidian-tag-navigator/issues/20

### CODE REVIEW

**Comment by alexobenauer** [comment]
@GeorgeHahn Excellent! Will dive into this in a few days when some time frees up for me.

**Comment by MartinBernstorff** [comment]
Hi Alex! 

Just a gentle nudge that this is here - the extension is awesome and provides a ton of value. Whether you get to it or not, thanks for writing it!

@GeorgeHahn, would you be interested in forking if Alex doesn't have the time?

**Comment by MartinBernstorff** [comment]
Oh, when I clone this and build it, it still seems broken on my end. Tried with a new vault with no extensions. Is this still working for you, @GeorgeHahn?

**Comment by GeorgeHahn** [comment]
@MartinBernstorff Yep, this is still working for me.

I'd be happy to help maintain the code if Alex would like a hand. I'm getting a lot of value out of this project and plan to keep using it for the foreseeable future. I don't have any interest in maintaining a fork though.

**Comment by caeochoa** [comment]
@GeorgeHahn I tried cloning and building your pull request, but #20 is still occurring for me. I'm still quite new to obsidian and Typescript, so I might be doing something wrong. I will try and look into the code and see if I can fix it on my end because the extension and the whole project look very promising for me –– do you have any ideas of where the problem could be?

**Comment by GeorgeHahn** [comment]
@caeochoa Could you walk me through the steps you took? One important point is that obsidian needs to be reloaded after you update the extension with the new build.

**Comment by caeochoa** [comment]
@GeorgeHahn you were right, it works now. I was just reloading the folder inside obsidian, but closing the app completely and opening it again did the trick. Thank you for this and for taking the time to make the pull request and share it!!

**Comment by MartinBernstorff** [comment]
I'm still unable to get it to work. Steps:

1. Clone the fork
2. Run `npm build` in the repo
3. Copy main.js and manifest.json into a new folder called `obsidian-tag-navigator`
4. Restart Obsidian

I can open the navigator pane, and press one of the pills to disable. After that, the pills aren't clickable.

Any ideas? Would love to use this! ❤️

**Comment by GeorgeHahn** [comment]
Try overwriting `main.js` on an existing tag navigator install

**Comment by clutterwhy** [comment]
Anyone mind to share the main.js if is working?

**Comment by alexobenauer** [comment]
@GeorgeHahn Diving into this now!

I'm getting a typescript error on this line: https://github.com/alexobenauer/obsidian-tag-navigator/pull/21/files#diff-6f81a51dcfc284044c5f7ba3ce259549ac7e3cf5c14ea1323d00add6e2c61d9bR44

**Comment by GeorgeHahn** [comment]
@alexobenauer Are your node modules updated? That line should be okay. We can switch back to the bool if it continues giving problems.

I added two commits: updated packages to the latest & updated the manifest's min app version to match that Keymap API.

**Comment by alexobenauer** [comment]
Perfect - this looks great @GeorgeHahn!

Will have this merged in & released shortly.

**Comment by eduongAZ** [comment]
Not sure if the issue will be fixed in the release, but I wanted to mention anyway:

I cloned and built the fork's source code and copied `main.js` and `manifest.json` into the folder `.obsidian/plugin/obsidian-tag-navigator`. I successfully enabled the plugin and used the command "Open Tag Navigator".

However, I only see the tags and I could click on the tags, but I do not see any notes that have the tags. I could click on the tag buttons to dim and un-dim the tags, and click the star to favorite, but no notes were shown and nothing seems to happen.

I am using Obsidian desktop (Mac) version 1.1.14

Am I using the plugin wrong? Was there a problem in the `npm install` and `npm run build` process? This seems like a fantastic plugin for my use-case (a lot of tags) and I really hope to be able to use it.

**Pull request closed without merging**
